import React, { useState } from 'react';
import { ArrowDown, ArrowUp, Check, ChevronRight, FlaskConical, GitBranch, MessageSquare, Play, Plus, Save, Trash2, X, Zap } from 'lucide-react';
import { actionNames, api, Empty, errorText, Field, Notice, rows, scopes, triggers, useResource } from './api';

const fields = { amount: 'Monto estimado (S/)', quantity: 'Cantidad de productos', is_company: 'Compra para empresa', text: 'Texto del mensaje', channel: 'Canal de origen' };
const operators = { gte: 'Mayor o igual a', gt: 'Mayor que', eq: 'Es igual a', contains: 'Contiene' };
const actionConfig = { send_reply: ['text', 'Mensaje de respuesta'], handoff: ['reason', 'Motivo de derivación'], create_task: ['text', 'Descripción de la tarea'], tag: ['tag', 'Etiqueta'] };
const blankFlow = () => ({ name: '', scope: 'store', trigger: 'incoming_message', enabled: false, priority: 100, conditions: [{ field: 'amount', operator: 'gt', value: 10000 }], actions: [{ type: 'qualify_lead', config: {} }, { type: 'offer_appointment', config: {} }] });

function WorkflowEditor({ initial, close, saved }) {
    const [flow, setFlow] = useState(() => structuredClone(initial)), [busy, setBusy] = useState(false), [error, setError] = useState('');
    const change = (key, value) => setFlow(previous => ({ ...previous, [key]: value }));
    const editCondition = (index, changes) => change('conditions', flow.conditions.map((condition, position) => position === index ? { ...condition, ...changes } : condition));
    const editAction = (index, changes) => change('actions', flow.actions.map((action, position) => position === index ? { ...action, ...changes } : action));
    const moveAction = (index, delta) => { const next = [...flow.actions]; [next[index], next[index + delta]] = [next[index + delta], next[index]]; change('actions', next); };
    const save = async event => {
        event.preventDefault(); setError(''); setBusy(true);
        try { await api(`/workflows${flow.id ? `/${flow.id}` : ''}`, { method: flow.id ? 'PUT' : 'POST', data: flow }); saved(); }
        catch (error) { setError(errorText(error)); } finally { setBusy(false); }
    };
    return <form className="ai-card ai-editor" onSubmit={save}>
        <div className="ai-section-heading"><div><span className="ai-kicker">EDITOR DE FLUJOS</span><h2>{flow.id ? flow.name : 'Crear un flujo de trabajo'}</h2><p>Los pasos se ejecutan en orden cuando se cumplen todas las condiciones.</p></div><button type="button" className="ai-icon-button" onClick={close} aria-label="Cerrar editor"><X size={20} /></button></div>
        <div className="ai-form-grid"><Field label="Nombre del flujo"><input autoFocus required maxLength={150} value={flow.name} onChange={event => change('name', event.target.value)} placeholder="Ventas corporativas y alto valor" /></Field><Field label="Prioridad" help="Un número menor se evalúa primero."><input type="number" min="1" max="1000" value={flow.priority} onChange={event => change('priority', Number(event.target.value))} required /></Field></div>
        <div className="ai-node-canvas">
            <section className="ai-workflow-node is-trigger"><div className="ai-node-title"><span><Zap size={18} /> 1. Disparador</span><small>CUANDO OCURRA</small></div><div className="ai-form-grid"><Field label="Origen"><select value={flow.scope} onChange={event => change('scope', event.target.value)}>{Object.entries(scopes).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Evento"><select value={flow.trigger} onChange={event => change('trigger', event.target.value)}>{Object.entries(triggers).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field></div></section>
            <div className="ai-node-connector"><ArrowDown size={18} /></div>
            <section className="ai-workflow-node is-condition"><div className="ai-node-title"><span><GitBranch size={18} /> 2. Condiciones</span><small>TODAS DEBEN CUMPLIRSE</small></div>
                {flow.conditions.length === 0 && <p className="ai-muted">Este flujo se aplica a todos los eventos del origen seleccionado.</p>}
                {flow.conditions.map((condition, index) => <div className="ai-condition-row" key={index}>
                    <Field label={`Campo ${index + 1}`}><select value={condition.field} onChange={event => { const field = event.target.value; editCondition(index, { field, operator: ['text', 'channel'].includes(field) ? 'contains' : ['is_company'].includes(field) ? 'eq' : 'gte', value: field === 'is_company' ? true : ['amount', 'quantity'].includes(field) ? 1 : '' }); }}>{Object.entries(fields).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>
                    <Field label="Comparación"><select value={condition.operator} onChange={event => editCondition(index, { operator: event.target.value })}>{Object.entries(operators).filter(([value]) => condition.field === 'is_company' ? value === 'eq' : ['amount', 'quantity'].includes(condition.field) ? value !== 'contains' : ['eq', 'contains'].includes(value)).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>
                    <Field label="Valor">{condition.field === 'is_company' ? <select value={String(condition.value)} onChange={event => editCondition(index, { value: event.target.value === 'true' })}><option value="true">Sí, es empresa</option><option value="false">No</option></select> : <input required type={['amount', 'quantity'].includes(condition.field) ? 'number' : 'text'} min="0" step="any" maxLength={300} value={condition.value ?? ''} onChange={event => editCondition(index, { value: ['amount', 'quantity'].includes(condition.field) ? Number(event.target.value) : event.target.value })} />}</Field>
                    <button type="button" className="ai-icon-button is-danger" aria-label={`Quitar condición ${index + 1}`} onClick={() => change('conditions', flow.conditions.filter((_, position) => position !== index))}><Trash2 size={17} /></button>
                </div>)}
                <button type="button" className="ai-button is-small" onClick={() => change('conditions', [...flow.conditions, { field: 'text', operator: 'contains', value: '' }])} disabled={flow.conditions.length >= 10}><Plus size={15} />Añadir condición</button>
            </section>
            <div className="ai-node-connector"><ArrowDown size={18} /></div>
            <section className="ai-workflow-node is-action"><div className="ai-node-title"><span><MessageSquare size={18} /> 3. Acciones</span><small>EN ESTE ORDEN</small></div>
                {flow.actions.map((action, index) => <div className="ai-action-row" key={index}><div className="ai-action-number">{index + 1}</div><div className="ai-action-fields"><Field label="Acción"><select value={action.type} onChange={event => editAction(index, { type: event.target.value, config: {} })}>{Object.entries(actionNames).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>
                    {actionConfig[action.type] && <Field label={actionConfig[action.type][1]}><textarea rows={2} maxLength={2000} required value={action.config?.[actionConfig[action.type][0]] || ''} onChange={event => editAction(index, { config: { ...action.config, [actionConfig[action.type][0]]: event.target.value } })} /></Field>}
                    {action.type === 'offer_appointment' && <p className="ai-muted">Ofrece horarios disponibles y recoge la confirmación del cliente antes de reservar.</p>}
                    {action.type === 'qualify_lead' && <p className="ai-muted">Registra el interés comercial para su seguimiento por el equipo.</p>}
                </div><div className="ai-action-tools"><button type="button" className="ai-icon-button" aria-label={`Subir acción ${index + 1}`} disabled={index === 0} onClick={() => moveAction(index, -1)}><ArrowUp size={16} /></button><button type="button" className="ai-icon-button" aria-label={`Bajar acción ${index + 1}`} disabled={index === flow.actions.length - 1} onClick={() => moveAction(index, 1)}><ArrowDown size={16} /></button><button type="button" className="ai-icon-button is-danger" aria-label={`Quitar acción ${index + 1}`} disabled={flow.actions.length === 1} onClick={() => change('actions', flow.actions.filter((_, position) => position !== index))}><Trash2 size={16} /></button></div></div>)}
                <button type="button" className="ai-button is-small" disabled={flow.actions.length >= 10} onClick={() => change('actions', [...flow.actions, { type: 'send_reply', config: { text: '' } }])}><Plus size={15} />Añadir acción</button>
            </section>
        </div>
        <Notice error={error} /><div className="ai-footer-actions"><label className="ai-inline-check"><input type="checkbox" checked={flow.enabled} onChange={event => change('enabled', event.target.checked)} />Activar al guardar</label><div className="ai-inline-actions"><button type="button" className="ai-button" onClick={close}>Cancelar</button><button className="ai-button is-primary" disabled={busy}><Save size={16} />{busy ? 'Guardando…' : flow.enabled ? 'Guardar y activar' : 'Guardar borrador'}</button></div></div>
    </form>;
}

function Simulator() {
    const [scope, setScope] = useState('store'), [trigger, setTrigger] = useState('incoming_message'), [context, setContext] = useState({ text: 'Necesito una cotización para mi empresa', amount: 12000, quantity: 12, is_company: true, channel: 'web' });
    const [result, setResult] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
    const change = (key, value) => { setContext(current => ({ ...current, [key]: value })); setResult(null); };
    const simulate = async event => {
        event.preventDefault(); setBusy(true); setError(''); setResult(null);
        try { setResult(await api('/simulate', { method: 'POST', data: { scope, trigger, context } })); } catch (error) { setError(errorText(error)); } finally { setBusy(false); }
    };
    return <form className="ai-card" onSubmit={simulate}><div className="ai-section-heading"><div><span className="ai-kicker">LABORATORIO</span><h2>Prueba un escenario</h2><p>Evalúa los flujos activos sin enviar mensajes ni reservar citas.</p></div><FlaskConical size={22} /></div>
        <div className="ai-form-grid"><Field label="Asistente"><select value={scope} onChange={event => { setScope(event.target.value); setTrigger(event.target.value === 'panel' ? 'panel_query' : 'incoming_message'); change('channel', event.target.value === 'whatsapp' ? 'whatsapp' : event.target.value === 'panel' ? 'panel' : 'web'); }}>{Object.entries(scopes).filter(([key]) => key !== 'all').map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="Evento"><select value={trigger} onChange={event => { setTrigger(event.target.value); setResult(null); }}>{Object.entries(triggers).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field>
            <Field label="Mensaje" wide><textarea rows={2} value={context.text} onChange={event => change('text', event.target.value)} maxLength={4000} /></Field><Field label="Monto (S/)"><input type="number" min="0" step="0.01" value={context.amount} onChange={event => change('amount', Number(event.target.value))} /></Field><Field label="Cantidad"><input type="number" min="1" step="1" value={context.quantity} onChange={event => change('quantity', Number(event.target.value))} /></Field></div>
        <div className="ai-footer-actions"><label className="ai-inline-check"><input type="checkbox" checked={context.is_company} onChange={event => change('is_company', event.target.checked)} />Compra para una empresa</label><button className="ai-button" disabled={busy}><Play size={16} />{busy ? 'Evaluando…' : 'Ejecutar prueba'}</button></div><Notice error={error} />
        {result && <div className="ai-simulation-result" role="status"><div className="ai-section-heading"><h3><Check size={17} />Prueba completada</h3><span className="ai-badge">Ejecución #{result.run_id || '—'}</span></div><p>{result.matched_rules?.length || 0} flujos coincidentes · {result.actions?.length || 0} acciones previstas.</p><div className="ai-simulation-tags">{(result.matched_rules || []).map((rule, index) => <span className="ai-badge" key={index}>{typeof rule === 'object' ? rule.name || `Flujo #${rule.id}` : `Flujo #${rule}`}</span>)}</div><ol className="ai-result-list">{(result.actions || []).map((action, index) => <li key={index}><strong>{actionNames[action.type] || action.type}</strong>{(action.config?.text || action.config?.reason || action.config?.tag) && <p>{action.config.text || action.config.reason || action.config.tag}</p>}</li>)}</ol>{!result.actions?.length && <p>Ajusta las condiciones o activa un flujo y vuelve a probar.</p>}</div>}
    </form>;
}

export default function WorkflowPanel() {
    const resource = useResource('/workflows'), [editing, setEditing] = useState(null), [error, setError] = useState(''), [success, setSuccess] = useState(''), [toggling, setToggling] = useState(null);
    const toggle = async flow => { setToggling(flow.id); setError(''); setSuccess(''); try { await api(`/workflows/${flow.id}`, { method: 'PUT', data: { ...flow, enabled: !flow.enabled } }); resource.refresh(); setSuccess(flow.enabled ? 'Flujo pausado.' : 'Flujo activado.'); } catch (error) { setError(errorText(error)); } finally { setToggling(null); } };
    return <div className="ai-stack"><div className="ai-section-heading"><div><h2>Automatizaciones con contexto</h2><p>Diseña recorridos para atender consultas, identificar oportunidades y acompañar al equipo.</p></div><button className="ai-button is-primary" onClick={() => { setEditing(blankFlow()); setSuccess(''); }}><Plus size={17} />Crear flujo</button></div><Notice error={error || resource.error} success={success} />
        {editing && <WorkflowEditor key={editing.id || 'new'} initial={editing} close={() => setEditing(null)} saved={() => { setEditing(null); resource.refresh(); setSuccess('Flujo guardado. Usa el laboratorio para comprobar sus condiciones.'); }} />}
        {!editing && <div className="ai-workflow-grid">{resource.loading ? <Empty>Cargando flujos…</Empty> : rows(resource.data).length === 0 ? <Empty>Crea tu primer flujo para empezar a automatizar.</Empty> : rows(resource.data).map(flow => <article key={flow.id} className="ai-card ai-flow-card"><div className="ai-section-heading"><span className={`ai-badge ${flow.enabled ? 'is-green' : ''}`}>{flow.enabled ? 'Activo' : 'Borrador / pausado'}</span><small>Versión {flow.version || 1}</small></div><h3>{flow.name}</h3><p>{scopes[flow.scope]} · {triggers[flow.trigger]}</p><div className="ai-mini-flow"><span><Zap size={17} />Evento</span><ChevronRight size={16} /><span><GitBranch size={17} />{flow.conditions?.length || 0} reglas</span><ChevronRight size={16} /><span><MessageSquare size={17} />{flow.actions?.length || 0} acciones</span></div><div className="ai-footer-actions"><button className="ai-button is-small" onClick={() => { setEditing(flow); setSuccess(''); }}>Editar flujo</button><button className={`ai-button is-small ${flow.enabled ? '' : 'is-primary'}`} disabled={toggling === flow.id} onClick={() => toggle(flow)}>{toggling === flow.id ? 'Guardando…' : flow.enabled ? 'Pausar' : 'Activar'}</button></div></article>)}</div>}
        <Simulator />
    </div>;
}
